### PR TITLE
Fixed #107 (partially): Converted all timezones to SG

### LINKED ISSUE #107: FOSSASIA: Set correct timezone of sessions in "Session JSON" and ensure correct timezone is set globally in "Event JSON"
In "Session JSON" the timezone is set to UTC. Please set SG timezone and ensure correct timezone is set globally in "Event JSON".

### PR DESCRIPTION
**Pull request by samyakbvs**
Changed UTC to SG

### CODE REVIEW

**Comment by samyakbvs** [comment]
@geekyd

**Comment by harshit98** [comment]
@samyakbvs Squash your commits.

**Comment by samyakbvs** [comment]
On it!

**Comment by geekyd** [comment]
The timezone is set by the open-event-server. All the applications in the open event ecosystem the server generated date/time. This is not needed. Please close this.

**Pull request closed without merging**
