### PR TITLE
New sample created for Hawaii'2016 by mozilla

### PR DESCRIPTION
**Pull request by mahikaw**
Adresses #131 
@mariobehling please review.

### CODE REVIEW

**Comment by mahikaw** [comment]
@mariobehling, for this particular event, the information for speakers is unavailable. The events defined in the official json provided by mozilla are different from the ones that are given under the speakers heading on the site. I am not sure about what I can do regarding this. 
Should I just make the speakers.json even if the events in it are actually different from the events in events.json?

**Comment by mariobehling** [comment]
Copy paste whatever information is available or create a script. I did not say that this task can be finished in a few minutes. The website has all the necessary information, e.g. https://hawaiiallhands2016.sched.com/directory/speakers and each speaker has its own page e.g. https://hawaiiallhands2016.sched.com/speaker/lcrouch1 Please use all information available and create a full sample of the event. 

I would expect this is obvious. I am not sure, where you need guidance.

We need a full sample in the Open Event format. I am sure you can make this happen.

**Comment by mariobehling** [comment]
Just to be sure. I recommend writing this sample as code instead of adding details and exporting it from eventyay. Eventyay samples are working, but might have some issues in regards to formatting. We need the samples on this repo to be human readable.

**Comment by mahikaw** [comment]
@mariobehling @niranjan94 I have completed the sample and updated it here. The APK is not functioning properly due to some errors with the generation process. Will provide a sample as soon as I'm able to figure that out.

**Comment by mariobehling** [comment]
@mahikaw So, there is still no update after 10 days? When will the sample be fully functional and ready for merge?

**Comment by mahikaw** [comment]
@mariobehling There were some issue with the app generator. The unzip functioned has been replaced and I have updated the docs yesterday only. I have been finally able to generate the app but there are serious issues with the app. I will be reporting them on the android repo today. 
I shall send the app on gitter if you want, however I am testing it. Cheers.

**Comment by niranjan94** [comment]
@mahikaw please don't close PRs and open new ones for the same issue. Update the existing PR. If you open a new one, we loose connection with all the conversation that happened in the previous PR.

**Comment by mahikaw** [comment]
Unfortunately, I don't have access to the branch @niranjan94 . So I had to create a new one.

**Comment by niranjan94** [comment]
Why didn't you have access to the branch ? It was on your repo right ?

**Comment by mahikaw** [comment]
No, I had re-forked it sometime back. I will take care of it in future.

**Pull request closed without merging**
