### PR TITLE
Updated SparkSummit17 sample

### PR DESCRIPTION
**Pull request by Jigar3**
#241 Updated the SparkSummit Sample according to the new API

### CODE REVIEW

**Comment by agbilotia1998** [comment]
@Jigar3 give a deployment link of the sample generated through web app generator.

**Comment by Jigar3** [comment]
Here is the deployment link:
https://jigar3.github.io/SparkSummit17/

**Comment by agbilotia1998** [comment]
@Jigar3 also the sample generated is not generated correctly.

**Comment by agbilotia1998** [comment]
@Jigar3 change the state key to accepted instead of draft in sessions json that would generate speakers .Rest I am debugging the remaining fields.

**Comment by mariobehling** [comment]
It seems like this PR has not been completed. I am closing this due to inactivity. Please open a new PR taking care of requested changes, if you are still interested to participate. Thank you.

**Pull request closed without merging**
