### PR TITLE
Apple WWDC Scrapped Data

### LINKED ISSUE #202: Sample for Apple WWDC 2017
Create Sample for Apple WWDC 2017 (https://developer.apple.com/wwdc/)

### PR DESCRIPTION
**Pull request by vaibhavsingh97**
Fixes #202 
Contributed by me and [Parth](https://github.com/ParthS007)

### CODE REVIEW

**Comment by mariobehling** [comment]
Thanks! Please provide a test page using the Open Event Web App Generator.

**Comment by mariobehling** [comment]
Please help to make it easier to get a review. I don't see a working example in the open event format. There Python scripts that are adjusted for the event. In this project we need more samples. It would be good. Please provide them and show a working example. Also check if images can be provided in more suitable sizes.

**Comment by ParthS007** [comment]
ok @mariobehling We will do this :+1:

**Comment by vaibhavsingh97** [comment]
@mariobehling Sure 👍

**Comment by mariobehling** [comment]
I am closing this due to inactivity. Please re-submit once you have a working sample. Cheers.

**Pull request closed without merging**
