### PR TITLE
add slogan and url fields in events

### PR DESCRIPTION
**Pull request by championswimmer**
re-data has got slogan and url fields, and it makes sense to have them .

@rafalkowalski @mananwason 
this should be merged only after the changes get reflected on all the three components (server, webapp, android)

### CODE REVIEW

**Comment by mananwason** [comment]
Cool :+1:

**Comment by rafalkowalski** [comment]
:+1:

**Comment by mananwason** [comment]
@rafalkowalski Where are you on this?

**Comment by rafalkowalski** [comment]
@mananwason I will add it as I finish switching between events

**Comment by mananwason** [comment]
Cool :+1:

**Comment by championswimmer** [comment]
status on this ?? :stuck_out_tongue:

**Comment by rafalkowalski** [comment]
it's added @championswimmer

**Comment by mananwason** [comment]
Done in the android app as well. So I am merging it.

**Pull request merged**
