### PR TITLE
renamed the google io and spark samples

### PR DESCRIPTION
**Pull request by arp95**
fixes: #172 and #176 
(gave a single pr because issues were minor)

@mariobehling 
please review.

### CODE REVIEW

**Comment by Princu7** [comment]
Looks good.

**Comment by Princu7** [comment]
In `config.json` you have not renamed the event. Plese, check it. Thanks

**Comment by arp95** [comment]
@Princu7 
done. please approve.

**Comment by arp95** [comment]
@Princu7 
just a doubt. in the session section do we need to specify speaker image and bio when they are already defined in the speaker section?
i mean we are linking them by ids right so in sessions.json when we list speakers is id and name fine?

**Comment by arp95** [comment]
@mariobehling made changes. see now.

**Pull request merged**
