### PR TITLE
added speaker Denelle Dixon

### PR DESCRIPTION
**Pull request by mahikaw**
Added the speaker with her details and social links.
Adresses #185

### CODE REVIEW

**Comment by arp95** [comment]
@mahikaw please resolve conflicts!

**Comment by mahikaw** [comment]
@arp95 @mariobheling please review.

**Comment by arp95** [comment]
@mahikaw 
use this one: https://www.linkedin.com/in/denelle-dixon-967a236/photo/

**Comment by mahikaw** [comment]
@mariobehling please review

**Pull request merged**
