### PR TITLE
PyCon 2017 Sample 

### PR DESCRIPTION
**Pull request by mahikaw**
Adresses #188
Event site:  https://us.pycon.org/2017/
Web app link: https://mahikaw.github.io/PyCon2017/

### CODE REVIEW

**Comment by mariobehling** [comment]
@mahikaw Please actively ask your co-developers for reviews using the "@" feature and pinging them on chat if necessary until you get your PRs approved. Cheers.

**Comment by mahikaw** [comment]
Sure @mariobehling

**Comment by Princu7** [comment]
There are some small issues with the sample. Please look at them. Thanks :)

* Some sessions contain an id of a speaker which doesn't exist in the speaker file.
* end_time of some sessions contain a space at the end of the string. It shouldn't be there.
* Some of the timings of sessions are not in proper format. Please look at them.

**Comment by mahikaw** [comment]
@Princu7 @arp95 @mariobehling  please review it. The web app has been deployed https://mahikaw.github.io/PyCon2017/

**Comment by mahikaw** [comment]
@mariobehling @niranjan94 @Princu7 @arp95 Please review.

**Comment by arp95** [comment]
@mahikaw 
nice work!
just some places i found mistakes.
1. logo should be of better quality
2. use better sponsor images, like some have black background can you look into that please?

**Comment by mahikaw** [comment]
@arp95 I couldn't find any other logo for PyCon 2017. Could you please suggest some other logo if you find it?
Also, the sponsor images don't fit well even after being square images. Will have to look at the web part of it. Also. are there any other required changes?

**Comment by niranjan94** [comment]
@mahikaw how about this ? https://caktus-website-production-2015.s3.amazonaws.com/media/blog-images/pycon-logo.jpg (A google image search gives this)

**Comment by mahikaw** [comment]
@niranjan94 Yes I had gone through this. It will have a white background again. It was decided against using logos with white backgrounds such as this in earlier samples by the mentors.

**Comment by niranjan94** [comment]
@mahikaw just removing the whitebackground and slightly cropping the images, gives a much better logo. 

**The cropped and corrected logo file:**
logo


**Result:**

screen shot 2017-07-10 at 12 47 35 pm

**Comment by niranjan94** [comment]
If you use logo with white background without doing anything, then it'll look bad. Crop it a bit such that there is no extra space around it and remove the white background (making it transparent). This will hardly take a a minute.

**Comment by mahikaw** [comment]
Thanks for this @niranjan94 Updated the sample. Please check it now https://mahikaw.github.io/PyCon2017/

**Comment by niranjan94** [comment]
The final logo output on the generated webpage is of very bad quality. https://mahikaw.github.io/PyCon2017/images/logo.png 

Does the generator do this ?

**Comment by mahikaw** [comment]
Yes. @niranjan94 I had used the image you provided above and generated the webapp. Probably the generator is doing something. I will look into it.

**Comment by Princu7** [comment]
@niranjan94 There is currently a constraint of the logo of allowing max-height of 45px (in order to not make the navbar section of too much long) and max width of 110px ( to not make the logo too wide). That's the condition along with ensuring that the aspect ratio of the image is not changed.

**Comment by niranjan94** [comment]
@Princu7 but looks like the resulting image is of too low quality. Especially when looking at in high-res displays. See the difference in the following two screenshots.

**Manually updated logo. Looks sharp and good.**
screen shot 2017-07-10 at 12 47 35 pm

**Logo output from the generator. Looks blurred and low quality.** 
screen shot 2017-07-10 at 1 24 49 pm

---

Please open an issue on the webapp repo to ensure the resized logo is of a good quality.

**Comment by Princu7** [comment]
@niranjan94 Ok, I will look into it in more detail. But, what most probably is happening is this:

* The logos of the event can be in high resolution and in order to save some space, we convert them into a suitable size at the generation step itself. It means that the above logo is converted to an appropriate size in accordance with the size constraints its aspect ratio (here the logo is resized to 78 * 45).

* The original logo image is in a much higher resolution (512 * 294). So, when we directly apply it on the navbar, it is appropriately resized (78 * 45) but is actually present in a much better quality.

So when we zoom or look at the image closely, the latter image looks sharper while the former appears blurred. It is because of the resizing step being done during the generation step. I will see what we can do in this case. Any suggestions on how to approach towards this problem would be great :smile: Thanks!

**Comment by Princu7** [comment]
Ok. I made some changes in the generator. The quality should be better now. Please check the test server
http://peaceful-earth-19050.herokuapp.com/

**Comment by mahikaw** [comment]
Thanks @Princu7 Please check the updated link https://mahikaw.github.io/PyCon2017/

**Comment by mahikaw** [comment]
@mariobehling Please review.

**Comment by mariobehling** [comment]
Some sponsors have a URL instead of their name displayed.

screenshot from 2017-07-24 09-44-19

**Comment by mariobehling** [comment]
I am merging this as work in progress. Thanks.

**Pull request merged**
