### PR TITLE
Fixes floors and sponsor_type 

### PR DESCRIPTION
**Pull request by mananwason**
@mariobehling Please review and merge. This adds sponsor_types to all sponsors and moves levels from the name to floor

### CODE REVIEW

**Comment by mariobehling** [comment]
Which issue is this related to? Please provide a description.

**Comment by mariobehling** [comment]
Why are there no tests performed for this PR?

**Comment by mananwason** [comment]
@mariobehling Updated the description but there are no tests that have been setup for this repo

**Comment by mananwason** [comment]
This is in reference too https://github.com/fossasia/open-event/issues/57 pt#3 and pt#4

**Comment by mariobehling** [comment]
Yes, you are right. Thank you.

**Pull request merged**
