### PR TITLE
Fixes #251 Updates Spark Summit Sample

### LINKED ISSUE #251: Update zip files of events
The zip files are not updated they are not using the new api format.

Update all the zip files for the events

### PR DESCRIPTION
**Pull request by ParthS007**
Updates Spark Summit Sample

Live Link : http://opev-webgen-dev.herokuapp.com/live/preview/parth1989shandilya@gmail.com/SparkSummit2017/

@mariobehling @geekyd Please review

**I will add it to overview site after merging of this PR**

### CODE REVIEW

**Comment by geekyd** [comment]
@ParthS007 The provided link is not working. Can you update the link?

**Comment by ParthS007** [comment]
done @geekyd  !

**Comment by geekyd** [comment]
@ParthS007 Why is the there only one page despite having all the data?

**Comment by ParthS007** [comment]
I have checked it, but I couldn't find any bug. Can you help me with it?

**Comment by agbilotia1998** [comment]
@ParthS007 the preview link is not working and instead of giving this preview link , generate the webapp on your local machine and deploy the generated sample on github , this would prevent the link expiry issue.

**Comment by geekyd** [comment]
@ParthS007 Have a look at #242. This PR is duplicate.

**Pull request closed without merging**
