### PR TITLE
Create version.json

### PR DESCRIPTION
**Pull request by the-dagger**
@mariobehling we will be needing this for the Android app, so could you please merge this?

### CODE REVIEW

**Comment by mariobehling** [comment]
@the-dagger The structure here does not correspond with the current structure of the folder and we dont have info about why we need a subfolder event/1/ instead of keeping the JSON files in the root.

**Comment by the-dagger** [comment]
@mananwason could you please explain the structure to @mariobehling. 
Thanks

**Comment by mananwason** [comment]
So @mariobehling In the app we are following the structure that we would have from a REST api hosted on a server and the api will have an endpoint like ``` /api/v1/event/{eventId}/speakers.json```.

**Comment by shivamMg** [comment]
> /api/v1/event/{eventId}/speakers.json

@mananwason Are you still using api version?

**Comment by mananwason** [comment]
@shivamMg I am not using the api version as such. That was just an example. I am using the version.json instead. So, anything before ```/event/{eventId}``` works for me.

**Comment by shivamMg** [comment]
@mananwason :+1:

**Comment by mariobehling** [comment]
This is actually the wrong place to discuss it as you are shutting people out from the discussion. There should have been an issue before the commit. 

@the-dagger @mananwason We are following the API structure in the JSON files, but I am unclear why we have to try to emulate it. The id of an event is already defined in the JSON file. It does not need to be defined in the folder structure.

**Comment by mariobehling** [comment]
I am closing this PR. Please make a new one after a decision has been taken that is supported by the team.

**Pull request closed without merging**
