### PR TITLE
fix: replaced all the conflicting attribute names in FOSSASIA16 sample

### PR DESCRIPTION
**Pull request by arp95**
fixes part of #190 

all the conflicting attribute names with old api are removed in the fossasia16 sample.

@iamareebjamal @Shailesh351 @shreyasnbhat @rohanagarwal94 @Princu7 
please review.

### CODE REVIEW

**Comment by Princu7** [comment]
@arp95 Looks Nice. I guess it would be better if you could also give the link to the script which you used for changing the attributes present in the different files. It is difficult to look at all the changes at once. Looking at the script would be less time consuming and efficient I guess.

I have incorporated the new recent API attributes change on the test server https://shrouded-ocean-89460.herokuapp.com and the app generates fine on it. There are unrelated problems with some of the speakers as their images are not showing up. I think that there is a typo in their name like the previous few issues that we solved. Yes, it is unrelated but can you also please look at that too? Thanks :)

**Comment by Princu7** [comment]
@arp95
This is the current test server which supports the new attributes in the current API models. If you want, you can generate a web app using it. Thanks :)
https://shrouded-ocean-89460.herokuapp.com

**Comment by arp95** [comment]
so for the new attribites i will just add them as empty strings, wgile for changed attributes will update them.
fine?

**Comment by arp95** [comment]
the script link is https://github.com/arp95/script_for_samples
please check this.

**Comment by mariobehling** [comment]
Merging this as work in progress. Thanks.

**Pull request merged**
