### PR TITLE
Corrected Spark summit invalid jsons

### LINKED ISSUE #233: Invalid speakers and sessions json in SparkSummit 17 sample.
Invalid characters found while webapp generator parses these jsons.

### PR DESCRIPTION
**Pull request by agbilotia1998**
Fixes #233

### CODE REVIEW

**Comment by agbilotia1998** [comment]
@mariobehling @geekyd please review.

**Comment by agbilotia1998** [comment]
@geekyd I intended to generate webapp for this from old API server (by the time if PR on open event webapp gets merged) . If everything goes fine we can add this event manually.

**Comment by agbilotia1998** [comment]
@mariobehling all speakers images are already square images and rest of the images are logos which are resized at the time of event creation. This is same convention as followed in all other samples.

**Comment by mariobehling** [comment]
Let's merge this as work in progress.

**Pull request merged**
