### PR TITLE
fix: added more information for the Google IO event

### LINKED ISSUE #152: Correct the sample event files of Google IO and Spark Summit event
There are some fields missing in Google IO event and Spark Summit event which are not giving a web app out of it. Correcting them.

### PR DESCRIPTION
**Pull request by arp95**
Adding the information for now. Will remove the [WIP] when complete.

fixes #152

### CODE REVIEW

**Comment by arp95** [comment]
@mariobehling @mahikaw @Princu7 
please review.
Link: https://arp95.github.io/GoogleIO_17/

**Comment by mahikaw** [comment]
@arp95 seems good. Please look into the following things:-

- Mention the event name in the issue and you can edit the issue description now that the PR is complete according to you.

- How have you selected the featured speakers? Some are missing and some of them seem extra I guess. For instance, the speaker right after Sundar Pichai in the keynote, Scott Huffmann is missing.

- Why is "Android" the track for keynote?

**Comment by arp95** [comment]
@mahikaw 
the issue still has spark event sample files to be added which i will do in another pr.

The featured speakers are selected on the basis of position and i think 150+ are ample enough for an event, you cant expect more!

For the keynote instance i know there was some issue. The issue here is its an individual event which doesnt have any track. So I thought putting it in Android one.

**Comment by mahikaw** [comment]
@arp95 

- I think you should create separate issues for different events. It'll be more clear then. 

- From what I took away from creating my last F8 sample, the keynote speakers are the most important. My suggestion would be that you go through this video for instance and then find out the keynote speakers. Also, remove the ones that aren't keynote.

- You should create a new "keynote" track as @mariobehling had once said on gitter.

**Comment by arp95** [comment]
@mahikaw thanks for pointing out.

Updated.
Link: arp95.github.io/GoogleIO_17/

@mariobehling @Princu7 please review.

**Comment by arp95** [comment]
@mahikaw doing it. please review a bit earlier from next time onwards. Thanks!

**Comment by arp95** [comment]
@mahikaw @Princu7 
please review.

**Comment by Princu7** [comment]
@arp95 Thanks. Looks Nice. Some of the pictures of speakers are not displaying. Might be because of a typo in the JSON file. Could you please check it? Thanks!!

**Comment by mahikaw** [comment]
In general looks good to me except for a few things-
@arp95 Could you look at the logo once? It has white background. Please use a logo that doesn't have a white background. 
Also, all the sponsors have the same "google products" link. Could you add product specific links instead?

**Comment by arp95** [comment]
@Princu7
can you look into the logo, how can we ensure to look ot good.
regarding sponsers @mariobehling should i remove sponsors as discussed?

**Comment by Princu7** [comment]
The logo looks a little out of place on the front page. On rest of the pages, it looks good. One thing we can do is remove the amount of white background in the image by cropping it. Or slightly darken the color of the background. Both are viable options. But, this issue should not be a blocker I guess.

**Comment by arp95** [comment]
fine then.
@mariobehling please review and merge.

**Comment by arp95** [comment]
Looks like the mentors are busy. Hence no point opening the pr for days or else i will again get a comment for pr being opened for days in the end.
Closing this for now.

**Pull request closed without merging**
