### PR TITLE
fix : Update Droidcon 2017 sample

### PR DESCRIPTION
**Pull request by Shailesh351**
Partially fixes : https://github.com/fossasia/open-event/issues/205

Changes:
- Fix inconsistent attributes
- Added remaining sessions in tracks and removed redundant sessions

### CODE REVIEW

**Comment by Shailesh351** [comment]
@Princu7 @mariobehling  Please review

**Comment by Shailesh351** [comment]
@Princu7 https://github.com/fossasia/open-event/wiki/%5BNextgen%5D-Open-Event-Universal-Format-Specification
In the Open Event Universal Format it is `audio-url` and `video-url` . Also server will return in this format. 
https://github.com/fossasia/open-event-orga-server/search?utf8=%E2%9C%93&q=audio_url&type=

**Comment by Princu7** [comment]
@Shailesh351 Oh! Sorry! I just saw the specs in the API docs. Guess, they would have to be updated. Thanks for informing!

**Comment by Shailesh351** [comment]
@mariobehling Please merge

**Pull request merged**
